## Build
FROM balenalib/raspberry-pi-debian-golang:latest as build

WORKDIR /app
COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . ./

RUN CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=7 go build -o /app/godog


## Deploy
FROM arm32v7/alpine:latest

WORKDIR /

COPY --from=build app/godog app/godog
WORKDIR /app

ENTRYPOINT ["./godog"]