## This is a multistage dockerfile for a smaller container at run-time.
## Build
FROM balenalib/raspberry-pi-debian-golang:latest as build

WORKDIR /godog
COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . ./

RUN go build

## Deploy
FROM balenalib/raspberry-pi-debian:latest-run

WORKDIR /

COPY --from=build /godog /godog
WORKDIR /godog
EXPOSE 1883
ENV UDEV=1

ENTRYPOINT ["./godog"]